#!/data/data/com.termux/files/usr/bin/bash

clear

figlet youtube | lolcat

figlet downloader | lolcat

sleep 1

clear

# code warna

a="\033[1;90m"

m="\033[1;91m"

h="\033[1;92m"

k="\033[1;93m"

b="\033[1;94m"

u="\033[1;95m"

c="\033[1;96m"

p="\033[1;97m"

echo -e "${c}+${a}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${c}+"

echo -e " ${p}{\033[1;96m•${p}} ${h}Author    ${m}: ${u}Randiansyah"

echo -e " ${p}{\033[1;96m•${p}} ${h}Facebook  ${m}: ${u}Rendi Kun"

echo -e " ${p}{\033[1;96m•${p}} ${h}Youtube   ${m}: ${u}Rendi Noober"

echo -e " ${p}{\033[1;96m•${p}} ${h}Fanspage  ${m}: ${u}Rendi Noober"

echo -e " ${p}{\033[1;96m•${p}} ${h}Instagram ${m}: ${u}rendinoober_"

echo -e "${c}+${a}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${c}+"

echo -e "              { MENU DOWNLOAD }"

echo

echo -e " \033[1;96m╠═▶ \033[1;92m1.Musik Mp3♫"

echo -e " \033[1;96m╠═▶ \033[1;92m2.Video 360p"

echo -e " \033[1;96m╠═▶ \033[1;92m3.Video 480p"

echo -e " \033[1;96m╠═▶ \033[1;92m4.Video 720p"

echo -e " \033[1;96m╠═▶ \033[1;92m5.Video 1080p"

echo -e "\033[1;97m"

command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/RENDI_NOOBER/%(title)s.%(ext)s -f'

read -p " ╚══➤ " option

if [ "$option" -eq "1" ]

then

    echo "$command 140" > ~/.config/youtube-dl/config

    youtube-dl $1

    echo "check on folder RENDI_NOOBER"

    sleep 2

elif [ "$option" -eq "2" ]

then

    echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config

    youtube-dl $1

    echo "check on folder RENDI_NOOBER"

    sleep 2

elif [ "$option" -eq "3" ]

then

    echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config

    youtube-dl $1

    echo "check on folder RENDI_NOOBER"

    sleep 2

elif [ "$option" -eq "4" ]

then

    echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config

    youtube-dl $1

    echo "check on folder RENDI_NOOBER"

    sleep 2

elif [ "$option" -eq "5" ]

then

    echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config

    youtube-dl $1

    echo "check on folder RENDI_NOOBER"

    sleep 2

else

    echo "WRONG COBA LAGI "

fi
